### ISSUE TITLE
move away from mixins

### ISSUE THREAD

**Issue by Haroenv** [firebase/reactfire#100]
As listed in [react/docs/reusable-components#no-mixins](https://facebook.github.io/react/docs/reusable-components.html#no-mixins) ES6 react doesn't support mixins anymore. I think it would be interesting to list in the documentation here how to handle this situation.

**Comment by jwngr** [comment]
Duplicate of #38.

**Comment by Haroenv** [comment]
Sorry, didn't see that issue. Thanks anyway :smile:
