### ISSUE TITLE
support the container component pattern

### ISSUE THREAD

**Issue by bigblind** [firebase/reactfire#102]
A big part of the ReactJS community is moving from using mixins to using container components, and composing them together. I'd like to propose a `createFirebaseContainer` function (or possibly just `createContainer`, which would work as follows:

```JavaScript
createFirebaseContainer(component, refs);
```
# arguments

  - **Component**:  The component you want to wrap
  - **refs**: a `FirebaseRefs` (see below) object or function that returns such anobject

If `refs` is a function, it should take in the props that were passed to the container when rendered, and returns a `FirebaseRefs` object.

# The `FirebaseRefs` object

A `FirebaseRefs` object, is an object that looks like this:

```JavaScript
{
  "<propName>": {
    "ref": DatabaseRef,
    "type": "array" | "object",
  }
  ...
}
```

Here, `"<propname>"` is the name of a property you want to receive. 
`ref` should be the database reference you want to bind that property to.
`type`should be either `"array"` or `"object"` depending on whether you want to bind to that reference as an array or an object.

# Example Usage

Here's an example for a `TodoList` component:

```JavaScript

const TodoList = React.createClass({
  render(){
    return <ul>
      {this.props.todos.map((todo) => {
        return <li><input type="checkbox" defaultChecked={todo.done}> {todo.text}</li>
      })}
    </ul>
  }
});

export default createFirebaseContainer(TodoList, {
  todos:  {
    ref: firebase.database().ref("/todos"),
    type: "array"
  }
});
```

Now, when you render the exported component, it would receive a `todos` prop, which represents the value in the database at `/todos`. When the value changes, the component is automatically re-rendered.

# Using a function for `refs`

You may not know in advance where the data you need lives. For example, a TodoList will likely only want to show todos for a specific user. These items could live at `/todos/{userID}`. To make it easier to specify the refs at runtime, you can pass a function like this:

```JavaScript
const TodoList = function(props) {
  return <ul>
    {props.todos.map((todo) => {
      return <li><input type="checkbox" defaultChecked={todo.done}> {todo.text}</li>
    })}
  </ul>
};

export default createFirebaseContainer(TodoList, (props) => {
  return {
    todos:  {
      ref: firebase.database().ref("/todos/" + props.userID),
      type: "array"
    }
  }
});
```

Now, assuming we import the exported component as `TodoList`, we can render it as `<TodoList userID="123abc" />`, and the todos for that user would be fetched.

# Advantages

The big advantage for this approach, is that we support more types of components. We don't rely on the component having state,, so we can write functional components, as seen above. We don't rely on the component having mixins, so we can support ES6 classes.

This also aligns it more with other popular libraries in the React ecosystem, such as Relay's [`createContainer`](https://facebook.github.io/relay/docs/guides-containers.html), and react-redux's [`connect`](http://redux.js.org/docs/basics/UsageWithReact.html#container-components) (though it uses a somewhat diffeent way of calling the function).

I'm willing to create a PR for this.

**Comment by bigblind** [comment]
I committed the mortal sin of not searching before opening an issue, and so completely missed the conversation in #38. Feel free to close this one.

**Comment by jwngr** [comment]
Thanks for copying this over to the other thread. I just responded on that thread, so let's keep the discussion there.
