### ISSUE TITLE
Iterating over bindAsArray items for .key

### ISSUE THREAD

**Issue by antsofthesky** [firebase/reactfire#116]
Using .map(), how would I be able to iterate over items to add the .key value within each object in the array, as an ID? 

```
{this.props.state.items.map((item, i) =>
      <li key={i} id={item.key}>{item.text}</li>
}
```

{item.key} doesn't render anything, it would seem that I'd need {item..key} but of course that throws a syntax error.

![screen shot 2016-09-28 at 9 24 58 pm](https://cloud.githubusercontent.com/assets/1593553/18938943/0f513df0-85c2-11e6-8628-c559916d8a4e.jpg)

**Comment by jwngr** [comment]
Use the bracket syntax: `item['.key']`.

I realize this is a bit of an annoyance, but see [this comment](https://github.com/firebase/reactfire/issues/55#issuecomment-134255278) for some background on why I chose `.key` versus something like `key` or `#key`. In a future version, I will probably make this configurable for those who want to change the default behavior.

**Comment by jwngr** [comment]
Also, in the future, please follow the issue template. It's there for a reason and honestly makes my life so much easier!

**Comment by antsofthesky** [comment]
Thank you, this works! The reasoning makes sense.
