### ISSUE TITLE
Not supported anymore?

### ISSUE THREAD

**Issue by sv** [firebase/reactfire#117]
Rhis implementation uses mixins which are not recommended by react anymore. There has been no updates for while as well. 
Could you please outline if there areany plans to move this lib further and what alternatives could you recommend

### Version info

**React:**

**Firebase:**

**ReactFire:**

**Other (e.g. Node, browser, operating system) (if applicable):**

**Comment by jwngr** [comment]
This is still supported, I just haven't found the time to finish my implementation with uses HOCs. Follow along at #38.
