### ISSUE TITLE
Add TypeScript / Flow typings

### ISSUE THREAD

**Issue by jwngr** [firebase/reactfire#119]
We should provide TypeScript and/or Flow typings for consumers of this repo. Does anyone have any preference for either? TypeScript seems more popular overall and is generally what we use with other Firebase repos, but Flow seems more popular in the React ecosystem due to the Facebook connection. Does anyone know how we can provide both in an easy way?

**Comment by fongandrew** [comment]
FWIW, Typescript also became pretty popular in the React ecosystem once they added JSX support. Plus if the main Firebase library is typed in TS, we'd have to use that anyway.

In any event, my understanding is that it's not too hard to convert from TypeScript definitions to Flow (https://github.com/joarwilk/flowgen).

**Comment by jwngr** [comment]
Yeah I think I will probably start with TS.

**Comment by cosminstefanxp** [comment]
👍

**Comment by theocodes** [comment]
howdy! Is this being worked on? help needed?

**Comment by samtstern** [comment]
We have officially deprecated reactfire, as we no longer believe it is the best solution for Firebase developers looking to integrate with React.

Please see the `README` for information on how to migrate to a better solution. We are working on some new efforts to better serve the React community in the future.
