### ISSUE TITLE
this.data not being cleaned up

### ISSUE THREAD

**Issue by EduardJS** [firebase/reactfire#120]
Hello! 🤙 

I'm building this messenger-like application, on top of React and Firebase, obviously, and, I've been pulling my hair out for more than 2 hours trying to find out what was causing the weird behavior. 

1. Upon login, I am listening to some rooms ( of users ), then upon room selection I start listening to messages belonging to that room. 

2. The issue arose when a user logs out, and then logs back in from another account for example.
Upon `componentWillUnmount` the references get unbinded, so that's all nice and cool.

3. So, logging back in with another user, even though there is no listener nor reference anymore, I am immediately seeing the "old" messages popping up inside the `ConversationView` component. 

After hours of trying to figure out what is happening.. I finally decided to start looking at what exactly is this mixin doing. Luckily, I quickly realised that we are storing reference data inside `this.data` but we're not deleting it when the reference gets unbinded. 

Therefore, my component's state was automatically being populated with the old reference values from within `this.data` which were saved when the previous account was logged in.

Note that it doesn't affect components which bind references inside `componentWillMount`, since those will pull new data anyway. But for the ones which are waiting for data to be binded... the "old" data ( from the previous bind -- previous logged in account ) gets sent towards the component's state once you bind any other reference.

I created a PR with a fix here #121 , which implies cleaning the unbinded variable, as it should.

**Comment by samtstern** [comment]
We have officially deprecated reactfire, as we no longer believe it is the best solution for Firebase developers looking to integrate with React.

Please see the `README` for information on how to migrate to a better solution. We are working on some new efforts to better serve the React community in the future.
