### ISSUE TITLE
reactfire 1.0.0 does not support firebase 4.0.0 with npm installation

### ISSUE THREAD

**Issue by pzmosquito** [firebase/reactfire#127]
### Version info

**React:** 15.5.4

**Firebase:** 4.0.0

**ReactFire:** 1.0.0

**Other (e.g. Node, browser, operating system) (if applicable):**

**Comment by TeMuNiDe** [comment]
+ no support for all firebase 4.x.x

**Comment by thevaleriemack** [comment]
+1

**Comment by samtstern** [comment]
We have officially deprecated reactfire, as we no longer believe it is the best solution for Firebase developers looking to integrate with React.

Please see the `README` for information on how to migrate to a better solution. We are working on some new efforts to better serve the React community in the future.
