### ISSUE TITLE
Upgrade node and dependencies version

### ISSUE THREAD

**Issue by BrodaNoel** [firebase/reactfire#129]
Guys,
If you want the community help, please, keep updated all npm dependecies and node versions.

Please, check all deprecation messages you get when running:
```bash
rm -rf node_modules
npm i
```

I recommend to add a `.nvmrc` file with the `v6.10` node version, then config travis to use it, and upgrade all dependencies in `package.json`.

After all those upgrades, ESLint will be in red, so you'll need to change 4 ESLint rules.

If you want me to do that upgrade, please add a new travis config to run the project using node 6.10 and let me know.

**Comment by BrodaNoel** [comment]
My idea is that after doing this upgrade, I'll add the `withFirebase` HOC to avoid using Mixins feature ([remember that Mixins are considered harmful](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html))

**Comment by BrodaNoel** [comment]
What I'll do is add the `withFirebase` HOC so then the dev will be able to do:
```jsx
var Xxx = React.createClass({
  componentWillMount: function() {
    this.props.bindAsArray(firebase.database().ref('foo'), 'data');
  },
  render: function() {
    return (
      ...
    );
  }
});

Xxx = withFirebase(Xxx);
`

**Comment by samtstern** [comment]
We have officially deprecated reactfire, as we no longer believe it is the best solution for Firebase developers looking to integrate with React.

Please see the `README` for information on how to migrate to a better solution. We are working on some new efforts to better serve the React community in the future.
