### ISSUE TITLE
Does reactfire work with the new Firestore service?

### ISSUE THREAD

**Issue by JCDJulian** [firebase/reactfire#130]
Not clear from the docs whether reactfire's bindings are only compatible with Real Time Database or whether the new Firestore service is supported.

**Comment by mloureiro** [comment]
Actually, I'm also interested in knowing this.
By reading the doc's it doesn't look like it

**Comment by samtstern** [comment]
We have officially deprecated reactfire, as we no longer believe it is the best solution for Firebase developers looking to integrate with React.

Please see the `README` for information on how to migrate to a better solution. We are working on some new efforts to better serve the React community in the future.
