### ISSUE TITLE
Filtering Firebase items loaded into state

### ISSUE THREAD

**Issue by AndroidDoctorr** [firebase/reactfire#131]
In the examples, it looks like the entire table is loaded into the state from Firebase. Those can get huge... Can you do something like a scan/query for select specific items, like with a text filter, or only items saved after a particular date?

**Comment by samtstern** [comment]
We have officially deprecated reactfire, as we no longer believe it is the best solution for Firebase developers looking to integrate with React.

Please see the `README` for information on how to migrate to a better solution. We are working on some new efforts to better serve the React community in the future.
