### ISSUE TITLE
This project is abandoned - use `react-redux-firebase` instead

### ISSUE THREAD

**Issue by christiangenco** [firebase/reactfire#132]
At the time of posting this comment, this project:

* hasn't been updated in 11 months
* is using the [old mixin style of passing down state](https://reactjs.org/blog/2016/07/13/mixins-considered-harmful.html), which fell out of favor in 2016
* doesn't support Firestore, which was [released in October of 2017](https://firebase.googleblog.com/2017/10/introducing-cloud-firestore.html)

[react-redux-firebase](https://github.com/prescottprue/react-redux-firebase) is under active development, uses higher order component composition (the recommended replacement for mixins), and [supports Firestore like a champ](http://react-redux-firebase.com/docs/firestore.html).

You'll need to learn [redux](https://redux.js.org/) to use it, but you should probably learn it anyway. The creator of Redux, Dan Abramov, has [a fantastic free course on learning redux for beginners](https://egghead.io/courses/getting-started-with-redux).

**Comment by peterlau** [comment]
Another option is https://github.com/tylermcginnis/re-base

`redux` brings with it a significant commitment and learning curve, which is often the right path but not always. In the latter case, I've found `re-base` to be a clean solution, whether used stand-alone, or in conjunction with `redux`.
