### ISSUE TITLE
Example featuring auth?

### ISSUE THREAD

**Issue by adamrneary** [firebase/reactfire#32]
This mixin is great, and the examples are very helpful, but I would love to see an example of how this works with authentication. 

Where in the process would we `ref.authWithCustomToken()` and `ref.unauth()` ?

Bonus: Are there best practices for auith error handling in a React component using the Reactfire mixin? What if the user is trying to access data to which he doesn't have access rights? 

An example capturing this would be awesome. I am happy to contribute, but I am not really sure how this should be done.

**Comment by jwngr** [comment]
Hey there, glad you found this mixin! The ReactFire mixing doesn't really concern itself with authentication. Anywhere in a React component, you can create a `Firebase` ref and call any of the `auth*()` methods off of it. That should just work without any extra mixins or code. Our [authentication documentation](https://www.firebase.com/docs/web/guide/user-auth.html#section-monitoring-authentication) has a bunch of example code for you which should work within React.

As for dealing with access permission denials, both [`bindAsArray()`](https://www.firebase.com/docs/web/libraries/react/api.html#section-bindAsArray) and [`bindAsObject()`](https://www.firebase.com/docs/web/libraries/react/api.html#section-bindAsObject) take an optional third parameter `cancelCallback` which will be passed an `Error` object whenever authentication fails. It is equivalent to the `cancelCallback` argument for the regular Firebase SDK's [`on()`](https://www.firebase.com/docs/web/api/query/on.html) method.

**Comment by adamrneary** [comment]
Sounds good, and thanks! I think the cancelCallback piece was what I was missing. Keep up the good work…

**Comment by quadsurf** [comment]
@jwngr ya but what about React Native... why is there no support for facebook or other social login? only email/password seems to work

**Comment by jwngr** [comment]
You'll need to use a third-party SDK to get an access token and then pass that access token to [`signInWithCredential()`](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInWithCredential). To get the Facebook access token, you can use [react-native-fbsdk](https://github.com/facebook/react-native-fbsdk).
