### ISSUE TITLE
ReactFire Auth with React Router

### ISSUE THREAD

**Issue by timlind** [firebase/reactfire#39]
Given the auth example on react-router, what's a recommended approach to obtain a reference to the firebase instance from the component's static willTransitionTo() function?

https://github.com/rackt/react-router/blob/master/examples/auth-flow/app.js#L46

**Comment by jwngr** [comment]
As someone who has never used `react-router`, you're probably gonna have to give me some more context here. What are you trying to do with the `Firebase` ref? Do you want to get the ref's auth state?

In general, you can create a `Firebase` reference whenever you want simply by doing:

```
var ref = new Firebase("https://<your-firebase>.firebaseio.com");
```

**Comment by jwngr** [comment]
Any comments @timlind? If not, I'm going to close this issue.

**Comment by timlind** [comment]
Hi @jwngr, 

That's useful to know the ref can just be re-created several times.

You're right, the need is to check the auth state on the ref. Seen as the willTransitionTo function is a static on the component that will be rendered at that route url, I was looking for a pattern of accessing the original Firebase ref from the static function, but it's more a react-router specific solution. That said, I imagine storing the ref in a component instead of an application wide accessible store, for instance, will be a problem with any router.
