### ISSUE TITLE
[0.5.0] Firebase.update failed: First argument  contains an invalid key (.key) in property

### ISSUE THREAD

**Issue by matiaslarsson** [firebase/reactfire#50]
I'm probably missing something obvious here but after upgrading to 0.5.0, when trying to update an existing record, I get `Uncaught Error: Firebase.update failed: First argument  contains an invalid key (.key) in property 'news.-XXXXXXXXXX'.  Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]"` from firebase-web.js:129 (v2.2.7)

This used to work in 0.4.0.

I'm loading the news item with;
```
var ref = new Firebase("https://XXXXXXXXXX.firebaseio.com/news/" + newsItemId);
this.bindAsObject(ref, "newsItem");
```
and updating the item with;
```
this.firebaseRefs["newsItem"].update(newsItem);
```
One of the changes in 0.5.0 was "ReactFire now adds the .key attribute to every record it creates via the bindAsArray() and bindAsObject() methods."

Of course I can do `delete newsItem[".key"];` before updating the item but surely that cannot be the solution? :)

Creating a new item still works since it does not contain the new ReactFire ".key" property and the ReactFire Todo and Comment Box examples never update an existing item so they never experience this error.

**Comment by jwngr** [comment]
The `.key` attribute is not a valid key name for the Firebase database. It is around merely for convenience but should be removed before writing back to the database. You should be able to safely do `delete item['.key']` to get rid of the attribute before you write to the database.

**Comment by dbkaplun** [comment]
Here's a nice regex you can use to validate Firebase keys: `const VALID_FIREBASE_KEY_RE = /^[^.#$\/\[\]]+$/`
