### ISSUE TITLE
Removing records from Firebase not reflecting correctly in app

### ISSUE THREAD

**Issue by martellaj** [firebase/reactfire#53]
Let me set the stage for you. Small todo list app. List of todo items are stored in a Firebase database, they have 2 properties (text and done). My todo list app has 2 ways to delete records from the database: delete individual items or delete all that are done.

I'm finding that if I have a list of 3 items, say A, B, and C, and I delete A, the list is rendered incorrectly and instead of being B, C it will be A, B, even though the correct item was deleted in the database and ReactFire returned the correct list of items! 

I'm unsure of what to do. You can see the code I'm having trouble with in a [branch I set up for you](https://github.com/martellaj/react-seed/tree/reactfire-array-update-issue), complete with your own db to play with (already added test items in for you). To run the code, just clone, npm install, and gulp.

Please reach out if I can provide anything else!

**Comment by jwngr** [comment]
Thanks for the bug report Joe. FYI that it'll probably be a couple days until I have time to look into this, but I'll get to it.

**Comment by martellaj** [comment]
Sounds good. I'm going to dig into it more and provide more info I can.

**Comment by martellaj** [comment]
Apparently explicitly setting unique keys on dynamic lists is important in React. Lesson learned. Y'all are good. Awesome library!

**Comment by jwngr** [comment]
Glad you got it worked out and are enjoying the library. Good luck with your project!
