### ISSUE TITLE
Discussion List

### ISSUE THREAD

**Issue by collin** [firebase/reactfire#63]
Is there a discussion list for reactfire? If there is it would be nice to have a link to it in the repo.

**Comment by jwngr** [comment]
Nope, there is no discussion list for ReactFire specifically. However, feel free to post questions on our [Firebase Google Group](https://groups.google.com/forum/#!forum/firebase-talk) or open issues on this repo. If we hear enough people ask for a discussion list, we will create like we have for AngularFire and EmberFire. Thanks for the suggestion!
