### ISSUE TITLE
Plan to upgrade react to v0.14

### ISSUE THREAD

**Issue by mzorzella** [firebase/reactfire#71]
Hi,
What is your plan to upgrade reactfire to react v0.14?

Thanks,
Michele

**Comment by jwngr** [comment]
We haven't gotten around to testing and upgrading the `bower.json` and `package.json` for React v0.14 yet. I'm hoping to spend some time going through the open issues in this repo within the next week or so and will get to this then.

Have you tried using this with React v0.14? Run across any issues I should know about?

**Comment by mzorzella** [comment]
Jacob, I'm in the process of trying it and I'll report back in the next couple of days. Thanks a lot.

**Comment by mzorzella** [comment]
Hi Jacob, I've been using reactfire for the last few days with react 0.14 and I've haven'r run across any issues so far.

**Comment by jwngr** [comment]
Great, thanks for letting me know. I just tried upgrading the `react` dependency to `0.13.x || 0.14.x` but there are some changes required to get the tests passing again. I was making progress until I hit [this open issue](https://github.com/facebook/react/issues/4461) which I'm not sure how to work around. I'll keep an eye on that issue and hopefully it gets fixed soon. Otherwise, I'll need to figure out how to test this thing without using the shallow renderer. If you have ideas, throw them my way!

**Comment by Downchuck** [comment]
Bug is fixed, checking status.

**Comment by jwngr** [comment]
Yeah, I'm just waiting for them to cut a new release.

**Comment by jwngr** [comment]
Status update: still waiting for React to cut a new release...

**Comment by alanpog** [comment]
Any news on this? There had been a few releases from React since that bug fix. Thanks.

**Comment by jwngr** [comment]
I tried out the latest version of React, but I still hit the testing issue despite them saying it was fixed... Didn't spend a lot of time on it after that. The branch is [here](https://github.com/firebase/reactfire/tree/jw-react-0-14) in case anyone has any ideas of how to get the tests passing.

**Comment by jwngr** [comment]
Just an update here: this is still not fixed in the latest release of React. As comments in [this bug](https://github.com/facebook/react/pull/5561) suggest, it should go out with the next release. At that point, the tests should finally pass once again and we can upgrade to React 0.14.

**Comment by jwngr** [comment]
React finally shipped a fix for the bug in ReactTestUtils! I just merged in a PR which updates ReactFire to use React 0.14.x. Thanks everyone for the patience.

I hope to cross of a couple more open issues over the weekend and get out a new release of ReactFire. Stay tuned!

**Comment by jwngr** [comment]
ReactFire `0.6.0` is out and supports React `0.14.x`. Thanks everyone for your patience!
