### ISSUE TITLE
Add support for react-native-Android 

### ISSUE THREAD

**Issue by yeso126** [firebase/reactfire#72]
I get the following error: 
    No transports available

**Comment by jwngr** [comment]
I have no idea what this means... Can you please provide more details? What versions of everything are you using? I've never used `react-native-android` so you're gonna have to help walk me through this a bit.

**Comment by puf** [comment]
Facebook is working (with the community) on getting WebSocket support for
Android into React Native. This should be available in React Native 0.13.

If it doesn't work yet in that version, you might want to file a bug report
on: https://github.com/facebook/react-native/pull/2839

**Comment by jwngr** [comment]
Ahh I see, so Firebase doesn't work on ReactNative for Android. In that case, there is nothing that can be done on this repo, so I'm going to close this issue.
