### ISSUE TITLE
not working with react native

### ISSUE THREAD

**Issue by ferologics** [firebase/reactfire#78]
I'm not sure what's wrong but basically it's not synching data, and doesn't say that anything is wrong.

The stackoverflow [question](http://stackoverflow.com/questions/34237797/how-to-use-reactfire-with-react-native)

the version is 0.5.1

my [code](https://github.com/ferologics/Pomodoro/blob/master/todayView.js)

if you want I can send you the link for firebase database as well

thanks

**Comment by jwngr** [comment]
[Also posted on StackOverflow](http://stackoverflow.com/questions/34237797/how-to-use-reactfire-with-react-native). Please avoid duplicating posts across channels in the future. Ask one place and we will help you out as soon as we can.

It looks like Puf answered you on StackOverflow, so I'm going to close this issue out.
