### ISSUE TITLE
shouldComponentUpdate nextState always equals this.state

### ISSUE THREAD

**Issue by gragland** [firebase/reactfire#79]
Been running into any issue where the shouldComponentUpdate function's nextState param is always equal to this.state making it impossible to see what data changed.

I managed to fix this issue by modifying reactfire to always clone this.data before calling setState:
```
this.setState( JSON.parse(JSON.stringify(this.data)) );
//this.setState(this.data);
```

To be honest, I'm not exactly sure why this worked.. maybe someone else can see what the issue is and propose a better solution.

**Comment by jwngr** [comment]
Hmm, I'm not aware of anyone else reporting an issue like this and I have never come across it myself. But that is definitely annoying and may be a bug on our end. Can you please provide a minimal repro via JSFiddle or Plunker and I'll take a look?

**Comment by jwngr** [comment]
Ping. Please provide a repro or I am going to close this issue.

**Comment by jwngr** [comment]
Closing due to lack of repro.
