### ISSUE TITLE
bindAsPrimitive

### ISSUE THREAD

**Issue by aj0strow** [firebase/reactfire#80]
When writing complex form components, it's practical to bind strings directly to state, instead of needing to check `".value"` each time. Alternatively if there was an option in `bindAsObject` to always map to `".value"`. 

It makes the workflow more challenging as is, because you can't firebase bind and link state on the same component state key (three-way binding) without writing all the code.

**Comment by jwngr** [comment]
> It makes the workflow more challenging as is, because you can't firebase bind and link state on the same component state key (three-way binding) without writing all the code.

Can you please go into more detail on what you mean by this? Showing some code would probably help clear things up.

FYI that the reason why we use `.value` is explained [here](https://github.com/firebase/reactfire/issues/55). I still think it provides more benefit than cost.

**Comment by aj0strow** [comment]
It's just a little awkward.

```js
// main form

  getInitialState () {
    return { coverImageUrl: { ".value": null } }
  },

  save () {
    let {coverImageUrl} = this.state
    this.coverImageUrl.set(coverImageUrl[".value"], done)
  },

  render () {
    <BannerBox valueLink={this.linkState("coverImageUrl")} />
  },


// form component

  setValue (value) {
    let {valueLink} = this.props
    valueLink.requestChange({ ".value": value })
  },

  render () {
    let bgStyle = {
      backgroundImage: 'url(' + valueLink.value[".value"] + ')',
    }
  },
```

It's not a huge thing, but why do i need the complexity of an extra `object[".value"]` when I could bind to `string | null` and avoid it?

**Comment by jwngr** [comment]
Ahh I see. I agree it can be a bit awkward, but I still think it's our best option given my comments in #55. The `linkState()` call is particularly awkward, but I think two-way data binding is a bit of a React anti-pattern and is almost always not the best solution. So I'd rather not optimize for that use case.

**Comment by aj0strow** [comment]
> I think two-way data binding is a bit of a React anti-pattern and is almost always not the best solution.

What's bad about it? It works fine for me ..

**Comment by jwngr** [comment]
See the warning at the top of [their docs](https://facebook.github.io/react/docs/two-way-binding-helpers.html) for it:

> Note:
If you're new to the framework, note that ReactLink is not needed for most applications and should be used cautiously.

One of the great parts of React is the one-way data flow and a move away from two-way data binding. A uni-directional data flow makes your apps easier to reason about. As such, two-way data binding is usually a React anti-pattern.

**Comment by aj0strow** [comment]
Yeah i hear that all the time but when i ask *why* nobody can tell me. Anyway, thanks for replying.

**Comment by jehoshua02** [comment]
@aj0strow 

> when i ask why nobody can tell me.

Forgive me for being direct, but he just did.

> A uni-directional data flow makes your apps easier to reason about.

For deeper understanding [read docs](https://facebook.github.io/react/docs/why-react.html) and watch [conference](https://www.youtube.com/watch?v=x7cQ3mrcKaY) [presentations](https://www.youtube.com/watch?v=i__969noyAM).
