### ISSUE TITLE
react 0.13.x dependency causes multiple react versions to be installed

### ISSUE THREAD

**Issue by tirsen** [firebase/reactfire#82]
Reactfire has a strict 0.13.x dependency. If you start using 0.14.x there is no error message, instead npm gladly installs two versions of react at the same time which causes an obscure and hard to debug error at runtime. The workaround is to use npm-shrinkwrap but that is very annoying. It would be much better if reactfire would just support anything above 0.13.

**Comment by jwngr** [comment]
Related issue: https://github.com/firebase/reactfire/issues/71

I did the work required to upgrade to `0.14.x`, but I haven't published a new release yet. I was hoping to get a few other fixes in before releasing, but I don't know when that will happen. So I'm just going to cut a new release now. I've [upgraded the `react` dependency to `0.14.x`](https://github.com/firebase/reactfire/blob/3ce65f1a131f4cdff81e4b708ee3dabb35aea599/package.json#L31), but I'm considering moving `react` and `firebase` from `dependencies` to `devDependencies`. [`react-router` follows this philosophy](https://github.com/rackt/react-router/blob/e8451bd10fc1b60da12ce92ad0930b86ffc0746f/package.json#L74) which means npm won't try to pull down multiple versions of React. I think this may solve a lot of the dependency problems I've had maintaining this library.

Do you have any feedback on that plan before I cut a new release?

**Comment by jwngr** [comment]
Okay, after doing some more research and reading [this](https://blog.domenic.me/peer-dependencies/), I'm pretty convinced that I should update `react` and `firebase` to be `peerDependencies` instead of regular `dependencies`. My plan is to cut a new release with the following dependencies in the `package.json`:

```
{
  "dependencies": {},
  "peerDependencies": {
    "firebase": "2.x.x",
    "react": "0.13.x || 0.14.x"
  },
  "devDependencies: {
    // ...
  }
}
```

**Comment by jwngr** [comment]
Okay, `0.6.0` is out and should resolve this issue both now and in the future!

**Comment by tirsen** [comment]
Yes, I also think peer dependency is the right way to go. Thanks for the really quick turn around time for this. It made my morning!
