### ISSUE TITLE
Upgrade dependency to include React 15.0.0

### ISSUE THREAD

**Issue by jwngr** [firebase/reactfire#87]
Change log for React 15.0.0 [here](https://facebook.github.io/react/blog/2016/04/07/react-v15.html).

I'll gladly take a PR from the community on this one if anyone sees this. We need to add `15.x.x` [here](https://github.com/firebase/reactfire/blob/df2e9998efa8e3fc0291c2387c8266ab61a3f409/package.json#L31) and [here](https://github.com/firebase/reactfire/blob/df2e9998efa8e3fc0291c2387c8266ab61a3f409/bower.json#L35) as well as upgrade all dev dependencies [here](https://github.com/firebase/reactfire/blob/df2e9998efa8e3fc0291c2387c8266ab61a3f409/package.json#L46-L48) to `15.x.x`. We also should update the React dependency numbers in the `README.md` [here](https://github.com/firebase/reactfire#downloading-reactfire). If all tests pass and the examples all still work, we should be good to ship it.

**Comment by ThariqS** [comment]
--> #89

**Comment by jwngr** [comment]
Just to close the loop here, this was shipped in version `0.7.0` a few weeks ago.
