### ISSUE TITLE
If using (React + Redux) and firebase as main backend database, how would i host the project?

### ISSUE THREAD

**Issue by jasan-s** [firebase/reactfire#90]
I want to use firebase as my main backend database storage, i also want to use Redux with React. I am just confused as to how i would host my project. I can't host on firebase i think since this will be a node app. I'm a Node newbie , so pardon me for being ignorant but if i use redux in client side only will npm compile to static js files where i can use firebase hosting?

**Comment by jwngr** [comment]
You can build a static website using React and Redux which can be hosted on Firebase. You don't need Node to run it, you just need Node to build it. Once the code is built though, you can deploy it to Firebase Hosting and everything will work smoothly.
