### ISSUE TITLE
React Firebase 3 Issue!

### ISSUE THREAD

**Issue by rsflow** [firebase/reactfire#93]
Hi,

I keep getting this error with the new SDK whenever I call Firebase functions
![screen shot 2016-05-19 at 6 24 25 pm](https://cloud.githubusercontent.com/assets/6751025/15401323/4b74382c-1def-11e6-99cf-b6e614c89277.png)
Does the new SDK work on React?

Thank You!

**Comment by chitopolo** [comment]
@rsflow 
It works for me, i had the same issue what i think you should do is 
`npm uninstall --save firebase and after that npm install --save fireabase`
That worked for me, now i'm trying to fix some other reactifre issues, I hope it helps!

**Comment by jwngr** [comment]
ReactFire has not yet been upgraded to the latest Firebase `3.x.x` SDK. Please be patient while we get #91 reviewed, tested, merged, and deployed.

**Comment by rsflow** [comment]
@chitopolo I did a clean install of all the modules but still didn't help. :( 
Did you get the same error? I checked the Firebase object from the `import Firebase from 'firebase'` and it's empty. Then I searched in the main repo for any `_firebase2.default` but no results.
@jwngr Great news thank you :)

**Comment by chitopolo** [comment]
@rsflow have you followed all[ this](https://firebase.google.com/docs/database/server/start#authenticate-with-admin-privileges) steps? You should review it again, because I think you might missed something, maybe the error is on you firebase.initializeApp config.
@jwngr How long could it take?

**Comment by moonman22** [comment]
i was having this problem trying out the new SDK for a React & Webpack setup and the only solution that worked with me was to make sure to import the browser version of the SDK as webpack was attempting to import the node version , using ES6 imports use this and it should work 
`import firebase from 'firebase/firebase-browser';` 
that of course regarding the SDK itself , React Fire doesn't work with it yet
hope that helps .

**Comment by rsflow** [comment]
@moonman22 Wow thank you very much ... finally it works. :) 
@chitopolo The solution @moonman22 gave worked. This issue is happening only to the react and webpack users.

**Comment by moonman22** [comment]
@rsflow Your are welcome , glad i could help .
