### ISSUE TITLE
Instructions seem to refer to index.html while TODO is in app.js

### ISSUE THREAD

**Issue by zahidirfan** [firebase/reactfire#95]
Setup Instructions

To run this example locally, either download the whole ReactFire repository or just this /commentsBox/ directory. Then replace the example Firebase URL with your own Firebase URL in the index.html file:

var firebaseApp = "https://my-firebase-app.firebaseio.com/"

**Comment by zahidirfan** [comment]
// IMPORTANT: Replace below with your Firebase app URL
var firebaseUrl = "https://my-firebase-app.firebaseio.com/";

**Comment by jwngr** [comment]
Thanks for reporting! I'll get this and #96 fixed soon.

**Comment by jwngr** [comment]
Should be fixed by #96.
